# Helm Chart Values for Hauler
# Docs: https://hauler.dev

hauler:
  image:
    repository: hauler/hauler
    tag: 1.2.0
  imagePullPolicy: Always

  initContainers:
    image:
      repository: rancher/kubectl
      tag: v1.31.3         # update to your kubernetes version
    imagePullPolicy: Always
    timeout: 1h

  data:
    pvc:
      accessModes: ReadWriteOnce
      # storageClass: longhorn # optional... will use default storage class
      storageRequest: 5Gi  # recommended size of 3x the artifact(s)
      test: true

  debug:
    enabled: false

# Helm Chart Values for the Hauler Jobs
# Docs: https://rancherfederal.github.io/hauler-docs/docs/introduction/quickstart
# Hauler Jobs are used to populate the Registry and/or Filestore with content
# Use "local" in order to populate the hauler store with locally available stores, hauls, and/or manifests.
# Use "remote" if these are remotely (HTTP/S/FTP/etc) available instead
# Simply comment out any unneeded values

haulerJobs:
  image:
    repository: hauler/hauler-debug
    tag: 1.2.0
  imagePullPolicy: Always
  # "remote" refers to URL-based hauler hauls and/or manifests
  remote:
    hauls:
      - path: https://raw.githubusercontent.com/hauler-dev/hauler/main/testdata/haul.tar.zst
        name: remhaul.tar.zst
      # - path: /path/to/additional-hauls.tar.zst
      #   name: additional-hauls.tar.zst
    manifests:
      - path: https://raw.githubusercontent.com/hauler-dev/hauler-helm/main/charts/hauler/ci/test-manifest.yaml
        name: remhauler-manifest.yaml
      # - path: /path/to/additional-manifests.yaml
      #   name: additional-manifests.yaml
  # "local" refers to the host the container/kubectl is being run on.  Use filesystem paths (hostDir) for these values.
  local:
    hauls:
      - path: /tmp/tests/
        name: local-haul.tar.zst
      # - path: /path/to/additional-hauls.tar.zst
      #   name: additional-hauls.tar.zst
    manifests:
      - path: /tmp/tests/
        name: local-manifest.yaml
      # - path: /path/to/additional-manifests.yaml
      #   name: additional-manifests.yaml
   # "store" refers to a previously created hauler folder structure.  See the "-s" argument to hauler.  Only one path is acceptable
  store: /tmp/hauler/store

# Helm Chart Values for the Hauler Fileserver
# Docs: https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-serve-fileserver
#

haulerFileserver:
  enabled: true
  port: 8080  # default port for the fileserver
  replicas: 1

  ingress:
    enabled: true
    hostname: fileserver.ranchers.io
    tls:
      enabled: true
      source: secret         # only supported source
      secretName: tls-certs  # must be created outside of this chart

  service:
    enabled: true
    type: ClusterIP
    ports:
      protocol: TCP
      port: 8080        # default port for the fileserver
      targetPort: 8080  # default port for the fileserver

# Helm Chart Values for the Hauler Registry
# Docs: https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-serve-registry

haulerRegistry:
  enabled: true
  port: 5000      # default port for the registry
  replicas: 1

  ingress:
    enabled: true
    hostname: registry.ranchers.io
    tls:
      enabled: true
      source: secret          # only supported source
      secretName: tls-certs   # must be created outside of this chart

  service:
    enabled: true
    type: ClusterIP
    ports:
      protocol: TCP
      port: 5000        # default port for the registry
      targetPort: 5000  # default port for the registry
